# Generated by Django 4.1.13 on 2026-01-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('userrole', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_login')),
            ],
        ),
    ]
