# Generated by Django 4.1.13 on 2026-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_property',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_property',
            name='area',
            field=models.PositiveIntegerField(default=1, help_text='Area in sq ft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
