# Generated by Django 4.1.13 on 2026-01-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_tbl_property_address_tbl_property_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='tbl_property',
            name='price',
        ),
    ]
