# Generated by Django 4.1.13 on 2026-01-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
        ('adminapp', '0001_initial'),
        ('UserApp', '0003_remove_tbl_property_area_remove_tbl_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plot_for_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('area', models.PositiveIntegerField(help_text='Area in sq ft or sq meters')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('water', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('gated_community', models.BooleanField(default=False)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='homeapp.tbl_user')),
                ('plot_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_plot_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_images/')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='UserApp.tbl_plot_for_sale')),
            ],
        ),
    ]
