# Generated by Django 4.1.13 on 2026-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_tbl_plot_for_sale_tbl_plot_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_plot_for_sale',
            name='plot_type',
            field=models.CharField(choices=[('Purayidam', 'Purayidam (Residential)'), ('Residential', 'Residential Plot'), ('Parambu', 'Parambu (Dry Land)'), ('Thottam', 'Thottam (Plantation)'), ('Vayal', 'Vayal (Paddy Land)'), ('Nilam', 'Nilam (Wet Land)'), ('Commercial', 'Commercial Plot'), ('Mixed', 'Mixed Use')], default='Purayidam', max_length=30),
        ),
    ]
