# Generated by Django 4.1.13 on 2026-02-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
        ('UserApp', '0005_alter_tbl_plot_for_sale_plot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_property')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1', to='homeapp.tbl_user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2', to='homeapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='UserApp.tbl_chat_room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
        ),
    ]
