# Generated by Django 4.1.13 on 2026-02-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
        ('UserApp', '0006_tbl_chat_room_tbl_chat_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbl_chat_room',
            unique_together={('user1', 'user2', 'property')},
        ),
        migrations.CreateModel(
            name='tbl_plot_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_plot_for_sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
            options={
                'unique_together': {('plot', 'user')},
            },
        ),
        migrations.CreateModel(
            name='tbl_plot_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_plot_for_sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
            options={
                'unique_together': {('plot', 'user')},
            },
        ),
    ]
