# Generated by Django 4.1.13 on 2026-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_tbl_chat_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_plot_interest',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_plot_interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
