# Generated by Django 4.1.13 on 2026-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='feedback_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('technical', 'Technical Issue'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
